### ISSUE TITLE
Eu removeria esse console.log, pois a função read que tem a responsabilidade de mostrar como está o array, podemos chamá-la quantas vezes quisermos.

### ISSUE THREAD

**Issue by felipebc11** [Jenyfferbastos/Learning-CRUD#2]
![image](https://user-images.githubusercontent.com/39533582/179403965-3bf2876e-7386-404f-b528-c4aa3f729d80.png)

**Comment by Jenyfferbastos** [comment]
![image](https://user-images.githubusercontent.com/107883696/180026119-df4f7ae1-ece5-4689-82c7-b7dee502df34.png)

Removido.

**Comment by felipebc11** [comment]
Pronto, excelente.
