### ISSUE TITLE
Aqui eu acho interessante chamar a função read após cada operação feita.

### ISSUE THREAD

**Issue by felipebc11** [Jenyfferbastos/Learning-CRUD#3]
![image](https://user-images.githubusercontent.com/39533582/179404041-40a9de62-33b4-4d03-b081-4d07b0466ccf.png)

Ficaria assim: 

```
read();

create("Julia", "11");

read();

update("Felipe", "23");

read();

deletePersons("Jenyffer", "18");

read();
```

**Comment by Jenyfferbastos** [comment]
![Captura de tela 2022-07-20 124328](https://user-images.githubusercontent.com/107883696/180025545-d70bb86b-53d7-4844-a090-9bf05b56e8e9.png)

Todas as funções agora estão sendo chamadas como no modelo acima.

**Comment by felipebc11** [comment]
Pronto, excelente.
